# Generated by Django 6.0.1 on 2026-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_sent', 'Pedido enviado'), ('product_sent', 'Producto enviado'), ('customer_sent', 'Cliente enviado'), ('error', 'Error')], max_length=50)),
                ('shopify_id', models.BigIntegerField(blank=True, null=True)),
                ('erp_response', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
