# Generated by Django 6.0.1 on 2026-01-20 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financial_status', models.CharField(max_length=50)),
                ('fulfillment_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.shop')),
            ],
        ),
    ]
