# Generated by Django 6.0.1 on 2026-01-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0005_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField()),
                ('product_title', models.CharField(max_length=255, verbose_name='Producto')),
                ('variant_title', models.CharField(blank=True, max_length=255, verbose_name='Variante')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shopify_app.order')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
            },
        ),
    ]
