# Generated by Django 6.0.1 on 2026-01-26 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0006_orderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verial_id', models.BigIntegerField(verbose_name='ID Verial')),
                ('verial_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU Verial')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verial_mapping', to='shopify_app.product')),
            ],
            options={
                'verbose_name': 'Mapeo de producto',
                'verbose_name_plural': 'Mapeos de productos',
            },
        ),
    ]
