# Generated by Django 6.0.1 on 2026-01-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0007_productmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmapping',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='verial_sku',
        ),
        migrations.AddField(
            model_name='productmapping',
            name='verial_barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código barras Verial'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='Código de barras')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('inventory_quantity', models.IntegerField(default=0, verbose_name='Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shopify_app.product')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
            },
        ),
        migrations.AddField(
            model_name='productmapping',
            name='variant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='verial_mapping', to='shopify_app.productvariant'),
            preserve_default=False,
        ),
    ]
