# Generated by Django 6.0.1 on 2026-01-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0008_remove_productmapping_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verial_id', models.BigIntegerField(verbose_name='ID Verial')),
                ('verial_nif', models.CharField(blank=True, max_length=20, verbose_name='NIF Verial')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verial_mapping', to='shopify_app.customer')),
            ],
            options={
                'verbose_name': 'Mapeo de cliente',
                'verbose_name_plural': 'Mapeos de clientes',
            },
        ),
    ]
