# Generated by Django 6.0.1 on 2026-01-27 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0009_customermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_verial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_verial_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('READY', 'Ready'), ('SENT', 'Sent'), ('ERROR', 'Error')], default='RECEIVED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='verial_error',
            field=models.TextField(blank=True),
        ),
    ]
