# Generated by Django 6.0.1 on 2026-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0010_order_received_at_order_sent_to_verial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verial_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
