# Generated by Django 6.0.1 on 2026-01-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0011_order_verial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verial_id', models.BigIntegerField(verbose_name='ID Verial')),
                ('verial_referencia', models.CharField(max_length=50, verbose_name='Referencia enviada')),
                ('verial_numero', models.CharField(blank=True, max_length=20, verbose_name='Número Verial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verial_mapping', to='shopify_app.order')),
            ],
            options={
                'verbose_name': 'Mapeo de pedido',
                'verbose_name_plural': 'Mapeos de pedidos',
            },
        ),
    ]
